### PR TITLE
Implemented parsing of ROOM_DATA_BYTES

### PR DESCRIPTION
**Pull request by BG-FraserConnolly**
Unity clients can now receive data sent from the server using client.sendBytes.

For a Unity client to register a call back for a message sent to it by the server using SendBytes, call RoomController OnMessage with the type byte[ ]

### CODE REVIEW

**Comment by endel** [comment]
Thank you for the PR @BG-FraserConnolly 💜

**Comment by BG-FraserConnolly** [comment]
Thanks for the quick approval @endel but I'm afraid I made a small mistake.

line 506 should be:
`else if (code == ColyseusProtocol.ROOM_DATA || code == ColyseusProtocol.ROOM_DATA_BYTES)`

I missed out the second code == when copying from my project to the pull request.

Do you want me to make a new pull request? Should this one be reverted?

**Comment by endel** [comment]
Hi @BG-FraserConnolly, can you send another PR please? That was an oversight from me as well

**Comment by BG-FraserConnolly** [comment]
@endel, Okay, I've submitted #229

**Comment by endel** [comment]
Thanks!

**Pull request merged**
